version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: python -m unittest discover
